service: tide-api
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'
    packExternalModulesMaxBuffer: 204800
functions:
  getLocations: ${file(apps/tide-api/src/functions/getLocations/getLocations.yml)}
plugins:
  - serverless-webpack
