service: tide-api
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  memorySize: 256 # default 1024 is way to much for nodejs
  logRetentionInDays: 14 # logs are shipped to ELK - no need to retain them longer in AWS (i/o SBP OPS)
  stackTags:
    GIT_SHA1: ${git:commit}
    GIT_BRANCH: ${git:branch}
    APP_VERSION: ${file(../../package.json):version}
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'
    packExternalModulesMaxBuffer: 204800
functions:
  getLocations: ${file(apps/tide-api/src/functions/getLocations/getLocations.yml)}
plugins:
  - serverless-webpack
  - serverless-plugin-git-variables
