import { Location } from './common';

/**
 * based on view-source:https://getij.rws.nl/
 * hardcoded for now
 */
export const TideLocations: Array<Location> = [
  { code: 'AMLAHVN-Amaliahaven', name: 'Amaliahaven' },
  { code: 'BAALHK-Baalhoek', name: 'Baalhoek' },
  { code: 'BATH-Bath', name: 'Bath' },
  { code: 'BERGSDSWT-BergseDiepsluisWest', name: 'Bergse Diepsluis west' },
  { code: 'BORSSLE-Borssele', name: 'Borssele' },
  { code: 'BRESKS-Breskens', name: 'Breskens' },
  { code: 'BROUWHVSGT02-BrouwershavenscheGat02', name: 'Brouwershavensche Gat 02' },
  { code: 'BROUWHVSGT08-BrouwershavenscheGat08', name: 'Brouwershavensche Gat 08' },
  { code: 'CADZD-Cadzand', name: 'Cadzand' },
  { code: 'DELFZL-Delfzijl', name: 'Delfzijl' },
  { code: 'DENHDR-DenHelder', name: 'Den Helder' },
  { code: 'DENOVBTN-DenOever', name: 'Den Oever' },
  { code: 'DORDT-Dordrecht', name: 'Dordrecht' },
  { code: 'EEMHVN-Eemhaven', name: 'Eemhaven' },
  { code: 'EEMSHVN-Eemshaven', name: 'Eemshaven' },
  { code: 'EURPHVN-Europahaven', name: 'Europahaven' },
  { code: 'GEULHVN-Geulhaven', name: 'Geulhaven' },
  { code: 'GOIDSOD-Goidschalxoord', name: 'Goidschalxoord' },
  { code: 'GOUDBG-GoudaBrug', name: 'Gouda brug' },
  { code: 'HAGSBNDN-HagesteinBeneden', name: 'Hagestein beneden' },
  { code: 'HANSWT-Hansweert', name: 'Hansweert' },
  { code: 'HARVT10-Haringvliet10', name: 'Haringvliet 10' },
  { code: 'STELLDBTN-Haringvlietsluizen', name: 'Haringvlietsluizen' },
  { code: 'HARLGN-Harlingen', name: 'Harlingen' },
  { code: 'HARMSBG-Harmsenbrug', name: 'Harmsenbrug' },
  { code: 'HARTBG-Hartelbrug', name: 'Hartelbrug' },
  { code: 'HARTHVN-Hartelhaven', name: 'Hartelhaven' },
  { code: 'HEESBN-Heesbeen', name: 'Heesbeen' },
  { code: 'HELLVSS-Hellevoetsluis', name: 'Hellevoetsluis' },
  { code: 'HOEKVHLD-HoekvanHolland', name: 'Hoek van Holland' },
  { code: 'HOLWD-Holwerd', name: 'Holwerd' },
  { code: 'HUIBGT-Huibertgat', name: 'Huibertgat' },
  { code: 'IJMDBTHVN-IJmuiden', name: 'IJmuiden' },
  { code: 'KATSBTN-Kats', name: 'Kats' },
  { code: 'KEIZVR-Keizersveer', name: 'Keizersveer' },
  { code: 'KORNWDZBTN-Kornwerderzand', name: 'Kornwerderzand' },
  { code: 'KRAMMSZWT-KrammersluizenWest', name: 'Krammersluizen west' },
  { code: 'KRIMPADIJSL-KrimpenAanDeIJssel', name: 'Krimpen aan de IJssel' },
  { code: 'KRIMPADLK-KrimpenAanDeLek', name: 'Krimpen aan de Lek' },
  { code: 'LAUWOG-Lauwersoog', name: 'Lauwersoog' },
  { code: 'LITHDP-LithDorp', name: 'Lith dorp' },
  { code: 'MAASSS-Maassluis', name: 'Maassluis' },
  { code: 'MARLGT-Marollegat', name: 'Marollegat' },
  { code: 'MOERDK-Moerdijk', name: 'Moerdijk' },
  { code: 'NES-Nes', name: 'Nes' },
  { code: 'NIEUWSTZL-NieuweStatenzijl', name: 'Nieuwe Statenzijl' },
  { code: 'OOSTSDE04-Oosterschelde04', name: 'Oosterschelde 04' },
  { code: 'OOSTSDE11-Oosterschelde11', name: 'Oosterschelde 11' },
  { code: 'OOSTSDE14-Oosterschelde14', name: 'Oosterschelde 14' },
  { code: 'OUDSD-Oudeschild', name: 'Oudeschild' },
  { code: 'OVLVHWT-OverloopVanHansweert', name: 'Overloop van Hansweert' },
  { code: 'PARKSS-Parksluis', name: 'Parksluis' },
  { code: 'PETTZD-PettenZuid', name: 'Petten Zuid' },
  { code: 'RAKND-RakNoord', name: 'Rak Noord' },
  { code: 'ROOMPBNN-RoompotBinnen', name: 'Roompot binnen' },
  { code: 'ROOMPBTN-RoompotBuiten', name: 'Roompot buiten' },
  { code: 'ROTTDM-Rotterdam', name: 'Rotterdam' },
  { code: 'ROZBSSNZDE-RozenburgsesluisNoordzijde', name: 'Rozenburgsesluis noordzijde' },
  { code: 'ROZBSSZZDE-Rozenburgsesluis zuidzijde', name: 'Rozenburgsesluis zuidzijde' },
  { code: 'SCHAARVDND-SchaarVanDeNoord', name: 'Schaar van de Noord' },
  { code: 'SCHEVNGN-Scheveningen', name: 'Scheveningen' },
  { code: 'SCHIERMNOG-Schiermonnikoog', name: 'Schiermonnikoog' },
  { code: 'SCHOONHVN-Schoonhoven', name: 'Schoonhoven' },
  { code: 'SINTANLHVSGR-Sint Annnaland', name: 'Sint Annaland' },
  { code: 'SPIJKNSE-Spijkenisse', name: 'Spijkenisse' },
  { code: 'STAVNSE-Stavenisse', name: 'Stavenisse' },
  { code: 'SUURHBNZDE-SuurhoffbrugNoordzijde', name: 'Suurhoffbrug noordzijde' },
  { code: 'TENNSHVN-Tennesseehaven', name: 'Tennesseehaven' },
  { code: 'TERNZN-Terneuzen', name: 'Terneuzen' },
  { code: 'TERSLNZE-TerschellingNoordzee', name: 'Terschelling Noordzee' },
  { code: 'TEXNZE-TexelNoordzee', name: 'Texel Noordzee' },
  { code: 'VLAARDGN-Vlaardingen', name: 'Vlaardingen' },
  { code: 'VLAKTVDRN-VlakteVanDeRaan', name: 'Vlakte van de Raan' },
  { code: 'VLIELHVN-VlielandHaven', name: 'Vlieland haven' },
  { code: 'VLISSGN-Vlissingen', name: 'Vlissingen' },
  { code: 'VURN-Vuren', name: 'Vuren' },
  { code: 'WALSODN-Walsoorden', name: 'Walsoorden' },
  { code: 'WERKDBTN-WerkendamBuiten', name: 'Werkendam buiten' },
  { code: 'WESTKPLE-Westkapelle', name: 'Westkapelle' },
  { code: 'WESTTSLG-WestTerschelling', name: 'West-Terschelling' },
  { code: 'WIERMGDN-Wierumergronden', name: 'Wierumergronden' },
  { code: 'YERSKE-Yerseke', name: 'Yerseke' },
  { code: 'AUKFPFM-Aukfieldplatform', name: ' Aukfield platfor' },
  { code: 'EURPFM-Europlatform', name: 'Euro platform' },
  { code: 'K13APFM-K13Aplatform', name: 'K13A platform' },
  { code: 'LICHTELGRE-LichteilandGoeree', name: 'Lichteiland Goeree' },
];
