name: Deploy master branch
on:
  push:
    branches:
      - master

env:
  NODE_VERSION: '12.x'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, and test
      run: |
        npm install
        npm run compile --if-present
        npm run test --if-present
    - name: serverless API deploy
      uses: serverless/github-action@v1.53.0
      with:
        args: deploy --config src/api/serverless.yml
      env:
        NODE_OPTIONS: '--max_old_space_size=8192'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
