name: Test & verify pull request
on:
  pull_request:
    branches:
      - master

env:
  NODE_VERSION: '12.x'

jobs:
  deploy:
    name: test & verify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, and test
      run: |
        npm install
        npm run compile --if-present
        npm run lint --if-present
        npm run test --if-present
